*** Starting uWSGI 2.0.15 (64bit) on [Sat Jul  1 19:55:57 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jul  1 19:55:57 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jul  1 19:55:58 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jul  1 19:59:29 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/fan/PycharmProjects/Arduino
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31069
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 3
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
Python main interpreter initialized at 0x55d0f60ee8e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 485760 bytes (474 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55d0f60ee8e0 pid: 3840 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3840)
spawned uWSGI worker 1 (pid: 3842, cores: 1)
spawned uWSGI worker 2 (pid: 3843, cores: 1)
spawned uWSGI worker 3 (pid: 3844, cores: 1)
spawned uWSGI worker 4 (pid: 3845, cores: 1)
spawned uWSGI worker 5 (pid: 3846, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./smarthome/views.py", line 40, in index
    i = info()
  File "./smarthome/views.py", line 15, in info
    ser = serial.Serial('/dev/ttyUSB0', 9600)
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
[pid: 3842|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 808 bytes} [Sat Jul  1 11:59:37 2017] GET / => generated 75740 bytes in 86 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 3843|app: 0|req: 1/2] 127.0.0.1 () {48 vars in 805 bytes} [Sat Jul  1 11:59:37 2017] GET /favicon.ico => generated 2061 bytes in 22 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./smarthome/views.py", line 40, in index
    i = info()
  File "./smarthome/views.py", line 15, in info
    ser = serial.Serial('/dev/ttyUSB0', 9600)
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
[pid: 3844|app: 0|req: 1/3] 114.253.83.232 () {44 vars in 779 bytes} [Sun Jul  2 15:24:39 2017] GET / => generated 75627 bytes in 62 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 3845|app: 0|req: 1/4] 114.253.83.232 () {42 vars in 708 bytes} [Sun Jul  2 15:24:40 2017] GET /favicon.ico => generated 2071 bytes in 16 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./smarthome/views.py", line 40, in index
    i = info()
  File "./smarthome/views.py", line 15, in info
    ser = serial.Serial('/dev/ttyUSB0', 9600)
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
[pid: 3846|app: 0|req: 1/5] 114.253.83.232 () {46 vars in 810 bytes} [Sun Jul  2 15:24:44 2017] GET / => generated 75762 bytes in 65 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./smarthome/views.py", line 40, in index
    i = info()
  File "./smarthome/views.py", line 15, in info
    ser = serial.Serial('/dev/ttyUSB0', 9600)
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
[pid: 3842|app: 0|req: 2/6] 114.253.83.232 () {46 vars in 810 bytes} [Sun Jul  2 15:24:46 2017] GET / => generated 75762 bytes in 47 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./smarthome/views.py", line 40, in index
    i = info()
  File "./smarthome/views.py", line 15, in info
    ser = serial.Serial('/dev/ttyUSB0', 9600)
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
[pid: 3843|app: 0|req: 2/7] 114.253.83.232 () {46 vars in 810 bytes} [Sun Jul  2 15:24:48 2017] GET / => generated 75762 bytes in 64 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sun Jul  2 22:52:12 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sun Jul  2 22:52:13 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Sun Jul  2 22:52:13 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sun Jul  2 22:52:15 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 21:54:57 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31051
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 21:54:57 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31051
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 21:54:58 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 21:54:59 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 21:55:00 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31051
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 22:33:10 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 22:33:10 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 22:33:11 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 22:33:11 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 22:33:11 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug  5 22:33:12 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 21:17:43 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 21:17:43 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 21:17:44 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 21:17:45 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 23:27:17 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 23:27:17 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 23:27:17 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 23:27:18 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** Starting uWSGI 2.0.15 (64bit) on [Fri Aug 11 23:27:19 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug 12 10:04:27 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug 12 10:04:27 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug 12 10:04:28 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /home/vitual/env_test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 4
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug 12 10:04:28 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
*** Starting uWSGI 2.0.15 (64bit) on [Sat Aug 12 12:00:11 2017] ***
compiled with version: 6.3.0 20170406 on 29 June 2017 22:17:11
os: Linux-4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017
nodename: fan-Venue-11-Pro-7130-MS
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/fan
writing pidfile to /home/fan/PycharmProjects/Arduino/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/fan/PycharmProjects/Arduino/
your processes number limit is 31060
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/fan/PycharmProjects/Arduino/arduino.sock fd 3
Python version: 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Set PythonHome to /home/vitual/env_test/
Python main interpreter initialized at 0x561f811ac070
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 485760 bytes (474 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x561f811ac070 pid: 11892 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11892)
spawned uWSGI worker 1 (pid: 11894, cores: 1)
spawned uWSGI worker 2 (pid: 11895, cores: 1)
spawned uWSGI worker 3 (pid: 11896, cores: 1)
spawned uWSGI worker 4 (pid: 11897, cores: 1)
spawned uWSGI worker 5 (pid: 11898, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vitual/env_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./smarthome/views.py", line 40, in index
    i = info()
  File "./smarthome/views.py", line 15, in info
    ser = serial.Serial('/dev/ttyUSB0', 9600)
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/vitual/env_test/lib/python3.5/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
[pid: 11894|app: 0|req: 1/1] 10.0.0.2 () {42 vars in 691 bytes} [Sat Aug 12 04:03:01 2017] GET / => generated 74873 bytes in 83 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 11895|app: 0|req: 1/2] 10.0.0.2 () {42 vars in 666 bytes} [Sat Aug 12 04:03:01 2017] GET /favicon.ico => generated 2061 bytes in 16 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
